import { Suspense } from 'react'
import './styles.scss'
import Loading from './loading'
import Header from './(routes)/components/header'

const name = 'Arshdeep Singh'

export const metadata = {
  title: 'Satoshi by Arsh',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='select-none overflow-x-none'>
        <Suspense fallback={<Loading />}>
          <Header />
          {children}
        </Suspense>
      </body>
    </html>
  )
}
